updated ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,9 +1,8 @@
 name: Full CI
 
 on:
-  push:
-    branches: [main, develop]
-  pull_request:
+  push:        
+  pull_request 
 
 jobs:
   backend:
@@ -12,8 +11,6 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
 
       - uses: actions/setup-go@v5
         with:
@@ -23,7 +20,7 @@ jobs:
         run: go mod download
 
       - name: Lint
-        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20
+        uses: golangci/golangci-lint-action@v6
         with:
           version: latest
 
@@ -69,10 +66,63 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
 
       - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
+        uses: SonarSource/sonarcloud-github-action@v2
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+  load-tests:
+    name: Load Tests (JMeter)
+    runs-on: ubuntu-latest
+    needs: backend
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Setup Java
+        uses: actions/setup-java@v4
+        with:
+          distribution: temurin
+          java-version: '17'
+
+      - name: Install JMeter
+        run: |
+          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
+          tar -xzf apache-jmeter-5.6.3.tgz
+          mv apache-jmeter-5.6.3 jmeter
+
+    
+      # APP_ENV=test нужен для тестового режима 
+      - name: Start services
+        run: |
+          APP_ENV=test docker compose up -d --build
+
+      - name: Wait for services
+        run: |
+          for i in {1..20}; do
+            curl -s http://localhost:8081/health && break
+            sleep 2
+          done
+
+      - name: Run JMeter test
+        run: |
+          ./jmeter/bin/jmeter \
+            -n \
+            -t tests/load_test.jmx \
+            -l results.jtl \
+            -e \
+            -o report
+
+      - name: Check results
+        run: |
+          if grep -q '"success":false' results.jtl; then
+            echo "Load test failed"
+            exit 1
+          fi
+
+      - name: Upload report
+        uses: actions/upload-artifact@v4
+        with:
+          name: jmeter-report
+          path: report/
